# This is a workflow that is manually triggered

name: release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to be released'
        required: true
      development-version:
        description: 'Next development version (without SNAPSHOT)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Release with Maven
      uses: qcastel/github-actions-maven-release@v1.11.2
      with:
        release-branch-name: "master"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -DdevelopmentVersion=${{ github.event.inputs.release-version }} -DdevelopmentVersion=${{ github.event.inputs.development-version }}-SNAPSHOT"

        maven-repo-server-id: repsy
        #maven-repo-server-username: ${{ secrets.REPSY_USER }}
        #maven-repo-server-password: ${{ secrets.REPSY_PASSWORD }}

        git-release-bot-name: "release-bot"
        git-release-bot-email: "software@befrish.de"

        #access-token: ${{ secrets.GH_TOKEN }}
